### ISSUE TITLE
PBKDF2WithHmacSHA512 Encryption example

### ISSUE THREAD

**Issue by Daniel-Wang** [rockaport/alice#10]
```
KeySpec ks = new PBEKeySpec(mnemonic, salt, 2048, 512);
SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
return skf.generateSecret(ks).getEncoded();
```

Hey @rockaport, what might this code look like using alice?

**Comment by rockaport** [comment]
Use the Alice context builder with iterations=2048. Double check that though.

**Comment by Daniel-Wang** [comment]
So something like this?
```
val aliceContext = AliceContextBuilder()
                        .setPbkdf(AliceContext.Pbkdf.PBKDF_2_WITH_HMAC_SHA_512)
                        .setIterations(2048)
                        .setKeyLength(AliceContext.KeyLength.valueOf("512"))
                        .build()
```
And sorry but how do I actually get my secret at the end like this `return skf.generateSecret(ks).getEncoded()`?

**Comment by rockaport** [comment]
Yes, but setKeyLength takes the enum version.

There's no API for getting the encoded key, it's all handled internally.

**Comment by Daniel-Wang** [comment]
Okay thanks, it looks like there's no enum for 512 though.
Got it, I use Alice to encrypt. In my case though, I'm looking to use the seed from this only

Basically, my problem is I'm trying to use [this](https://github.com/Soneso/stellar-java-mnemonic/blob/master/src/main/java/com/soneso/stellarmnemonics/mnemonic/Mnemonic.java) (line 58) library to create a seed from a mnemonic. But `SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512")` is not compatible for Android devices below API 26. So I need to implement this in another way, looking at alice

**Comment by rockaport** [comment]
If you want to use an already derived key then use [NONE](https://rockaport.github.io/alice/) and create it externally and pass it as an argument.

The reason there's no KeyLength larger than 256 is that none of the modes support larger keys, so having a larger one wouldn't do anything.

I think you need to use a different provider in order to get that to work on Android. Something like spongycastle.

**Comment by Daniel-Wang** [comment]
Yes thanks, I need to use SpongyCastle
