### ISSUE TITLE
Encryption output

### ISSUE THREAD

**Issue by Dave811** [rockaport/alice#12]
Hi,
I want to use your library in a project of mine and I need to get the encrypted output as a string with UTF-8 format. Is that possible?
I use that: 
`AliceContext aliceContext = new AliceContextBuilder()
                .setAlgorithm(AliceContext.Algorithm.AES)
                .setMode(AliceContext.Mode.CBC) // or AliceContext.Mode.CTR
                .setIvLength(16)
                .setPadding(AliceContext.Padding.PKCS5_PADDING)
                .setPbkdf(AliceContext.Pbkdf.PBKDF_2_WITH_HMAC_SHA_512)
                .setMacAlgorithm(AliceContext.MacAlgorithm.HMAC_SHA_512)
                .build();`
And to get the output I use that: 
`byte[] d = alice.encrypt(toEncrypt.getBytes(), secretKey.toCharArray());
            System.out.println(new String(d));
            System.out.println(new String(alice.decrypt(d, secretKey.toCharArray())));`
But the output looks like: 
`�8ӤÖz�>�$����B+4�\kLA{R�a
Bŋ���֒b\ا�	�]j�.��?�r�$j"RɫIܪ��C�>p��~L]�����\��R3;!p�.��T������Ѫ&�r �TK<{>A�HN�?�07�nϳ�U�ؑ<X����j����YA<K�dы�BP+9�`
Do you have an idea to get an output that is sharable?

**Comment by rockaport** [comment]
You probably want to base64 or hex encode the encrypted data. The do the
reverse before decrypting. It's pretty common to base64 encode it.

**Comment by Dave811** [comment]
Thank you!
This is what I was searching for.
Have a great day!
