### ISSUE TITLE
alice:0.9.0 Error on Android Studio 3.3.2

### ISSUE THREAD

**Issue by exmorrcmos** [rockaport/alice#13]
When I add the following line to gradle 
**implementation 'com.github.rockaport:alice:0.9.0'**
and building the project , I encounter the following error
**Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26).**

what is the problem?

**Comment by rockaport** [comment]
Groovy is being passed as a transitive dependency and you need to exclude that. I'm going to fix this in a later version. In the meantime just use this:
```
implementation('com.github.rockaport:alice:0.9.0') {
    exclude group: 'org.codehaus.groovy', module: 'groovy-all'
}
```

**Comment by exmorrcmos** [comment]
Thanks.
I did this and the previous error was fixed. But the app runs only on Android 8.0. In other versions of Android, an **_GeneralSecurityException_** error occurs when encrypting a file.
in android 7.0 ==>**_PBKDF2WithHmacSHA512 SecretKeyFactory not available_**
in android 4.1 ==>**_SecretKeyFactory PBKDF2WithHmacSHA512 implementation not found_**

**Comment by rockaport** [comment]
Right, you can see here that the support depends on the API level.
PBKDF2withHmacSHA1 is fine to use.

https://developer.android.com/reference/javax/crypto/SecretKeyFactory

**Comment by exmorrcmos** [comment]
thank you.
Can your library implement this type of encryption(PBKDF2withHmacSHA1)?
if yes , Could you provide an example of encrypting a file with this method?
Thanks again!

**Comment by rockaport** [comment]
Yes, use [AliceContextBuilder](https://rockaport.github.io/alice/com/rockaport/alice/AliceContextBuilder.html) and the [setPbkdf ](https://rockaport.github.io/alice/com/rockaport/alice/AliceContextBuilder.html#setPbkdf-com.rockaport.alice.AliceContext.Pbkdf-) method.

**Comment by exmorrcmos** [comment]
Thanks.
It's working.
