### ISSUE TITLE
SecretKeyFactory PBKDF2WithHmacSHA512 implementation not found

### ISSUE THREAD

**Issue by abayomiAkanji** [rockaport/alice#3]
Hi @rockaport thanks for this library.

I got this error log `SecretKeyFactory PBKDF2WithHmacSHA512 implementation not found`
Any work-around for it?

Thanks in anticipation.

**Comment by rockaport** [comment]
That's odd. What JRE and version are you running, OpenJDK or OracleJDK? It's available in in the Java8 [SunJCEProvider](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SunJCEProvider)

**Comment by abayomiAkanji** [comment]
Thanks for the prompt response. It's JDK 1.8

**Comment by rockaport** [comment]
Depending on your OS, can you run `which java` or `where java` in a command line/terminal and post your results? Does PBKDF_2_WITH_HMAC_SHA_1 throw the same exception?

**Comment by abayomiAkanji** [comment]
Hi @rockaport your prompt responses are well appreciated. Running `which java` on terminal (MacOS) returns `/usr/bin/java`

**Comment by rockaport** [comment]
The only thing I can think of is you're not using java 8. Running `java -version` should confirm which one you're running.

**Comment by abayomiAkanji** [comment]
Running `java -version` returns 
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by rockaport** [comment]
Do any of the other secret key factory modes work?

**Comment by abayomiAkanji** [comment]
@rockaport , I didn't understand your last question. Do you mean using another version of JAVA?

**Comment by rockaport** [comment]
Do any of the other secret key factory modes work?

**Comment by abayomiAkanji** [comment]
Oh, kindly explain how to change or use another secret key factory mode.

Thanks @rockaport

**Comment by rockaport** [comment]
Using the context builder setPbkdf method. Have a look at the unit tests for examples. The unit tests excercize all the different combinations of configurations, including the pbkdf modes.

**Comment by abayomiAkanji** [comment]
Many thanks for your support @rockaport 
Setting `Pbkdf` to `AliceContext.Pbkdf.PBKDF_2_WITH_HMAC_SHA_1` resolved the exception.

Once again, thank you. Your Twitter handle?
