### ISSUE TITLE
Gives the following error on android studio 3.0.1

### ISSUE THREAD

**Issue by neemashahbazi** [rockaport/alice#6]
Having it added in gradle,on run the following error is given:
`Information:Gradle tasks [:app:assembleDebug]
Warning:Ignoring InnerClasses attribute for an anonymous inner class
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/nimashahbazi/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.1/a9ca9c9de09361ec2a18d2c058d2524fbd8eae0c/groovy-all-2.4.1.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/codehaus/groovy/vmplugin/v7/IndyInterface.class
Error:com.android.dx.cf.code.SimException: signature-polymorphic method called without --min-sdk-version >= 26
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/nimashahbazi/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.1/a9ca9c9de09361ec2a18d2c058d2524fbd8eae0c/groovy-all-2.4.1.jar
Information:BUILD FAILED in 10s
Information:4 errors
Information:1 warning
Information:See complete output in console`

Any ideas? Thanks

**Comment by rockaport** [comment]
The problem is groovy is a compile dependency. That's probably something I
should figure out how to fix, but try excluding the groovy transitive
dependency.

https://stackoverflow.com/questions/30942825/exclude-package-from-gradle-dependency
