### ISSUE TITLE
Zip file gets corrupted after encryption...

### ISSUE THREAD

**Issue by neemashahbazi** [rockaport/alice#7]
I have been trying to encrypt a zip file using different algorithms presented in the library. The file is encrypted and decrypted and when I try to to unzip it, seems like the file is corrupted...
I have tried many compression tools and seems like this is happening because of the encryption process. Have you ever faced anything like that and any ideas on what needs to be done?

**Comment by rockaport** [comment]
It's probably because of the padding. When you encrypt use padding and when
you decrypt don't use padding.
