### ISSUE TITLE
The lib works only with min android 8 !!

### ISSUE THREAD

**Issue by florindumitru** [rockaport/alice#8]
Hi, can you help me pls because the lib works only with min android 8 and I need to work with min android 6

**Comment by florindum** [comment]
if I use this:
    implementation ('com.github.rockaport:alice:0.8.0'){
        transitive = false;
    }
then the apk build is OK but when I run it to a device with sdk version 24 I get this error at encryption:

ava.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA512 SecretKeyFactory not available
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:249)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:287)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at com.rockaport.alice.Alice.derivePbkdfKeyBytes(Alice.java:621)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at com.rockaport.alice.Alice.deriveKey(Alice.java:589)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at com.rockaport.alice.Alice.encrypt(Alice.java:178)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at app.r13.com.r13.Home.encrypt(Home.java:95)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at app.r13.com.r13.Home.access$000(Home.java:43)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at app.r13.com.r13.Home$1.onClick(Home.java:148)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.view.View.performClick(View.java:5637)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-21 21:52:00.360 3725-3725/app.r13.com.r13 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by florindum** [comment]
Okkk... I fixed by adding to alicecontext 
.setPbkdf(AliceContext.Pbkdf.PBKDF_2_WITH_HMAC_SHA_1)
+
implementation ('com.github.rockaport:alice:0.8.0'){
transitive = false;
}

In my case I was needed to add 
implementation 'com.squareup.okio:okio:1.14.0'
to make it work

**Comment by rockaport** [comment]
I've removed the okio dependency in v0.9.0
